#!/bin/sh

#perl -e 'print "HEAD / HTTP/1.0\n\n"' | nc localhost 80

function usage
{
  echo "Usage: getbanner <host> <port>"
  exit
}

if [ $# -ne 2 ]; then
  usage
fi

target=$1
port=$2

perl -e 'print "HEAD / HTTP/1.0\n\n"' | nc $target $port

